#!/usr/bin/env bash
# White-label build (lifetimedealsbundle.com)
#
# Produces a deployment with ZERO AffiliRank/affilirank.com surface area:
#  - removes the AffiliRank product page (/affilirank)
#  - REBRANDS the sales funnel (public/funnel/*) with the white-label brand
#    (name, tagline, logo, links) at build time via sed + a generated brand.js.
#    The affilirank.com build never runs this script, so its funnel is untouched.
#
# Everything else (name, tagline, tag, product-page gating, sitemap) is driven
# by NEXT_PUBLIC_* env vars at build time — see src/lib/constants.ts.
set -euo pipefail

# Escape a value for safe use inside a sed replacement (delimiter is `|`).
sed_rep() {
  local s="$1"
  s="${s//\\/\\\\}"
  s="${s//&/\\&}"
  s="${s//|/\\|}"
  printf '%s' "$s"
}

# Quote a value as a JS string literal.
js_str() {
  local s="$1"
  s="${s//\\/\\\\}"
  printf "'%s'" "${s//\'/\\\'}"
}

echo "> White-label build"

# ---- 1) Strip the AffiliRank-only product page (keep /funnel redirect route) --
if [ -d src/app/affilirank ]; then
  rm -rf src/app/affilirank
  echo "  removed src/app/affilirank"
fi

# ---- 2) Rebrand the sales funnel in place --------------------------------
FUNNEL_DIR="public/funnel"
if [ -d "$FUNNEL_DIR" ]; then
  BRAND_NAME="${NEXT_PUBLIC_SITE_PRODUCT_NAME:-${NEXT_PUBLIC_SITE_NAME:-AffiliRank}}"
  TAGLINE="${NEXT_PUBLIC_SITE_TAGLINE:-}"
  LOGO="${NEXT_PUBLIC_SITE_LOGO_URL:-}"
  SITE_URL_VAL="${NEXT_PUBLIC_SITE_URL:-}"
  HOST=""
  if [ -n "$SITE_URL_VAL" ]; then
    HOST="${SITE_URL_VAL#https://}"
    HOST="${HOST#http://}"
    HOST="${HOST%%/*}"
  fi

  BRAND_REP="$(sed_rep "$BRAND_NAME")"
  TAGLINE_REP="$(sed_rep "$TAGLINE")"

  # Wordmark HTML: split the product name, last word gets the gradient span.
  read -ra _words <<< "$BRAND_NAME"
  WM=""
  for ((_i = 0; _i < ${#_words[@]} - 1; _i++)); do WM+="${_words[_i]} "; done
  WM+="<span>${_words[${#_words[@]} - 1]}</span>"

  echo "  rebranding funnel -> ${BRAND_NAME} (host: ${HOST:-unset})"

  # Token replacement across every static funnel file (html, css, config.js).
  for f in "$FUNNEL_DIR"/*.html "$FUNNEL_DIR"/*.css "$FUNNEL_DIR"/*.js; do
    [ -f "$f" ] || continue
    # Wordmark: Affili<Rank> -> <LastWord> gradient split.
    sed -i "s|<span class=\"wordmark\">Affili<span>Rank</span></span>|<span class=\"wordmark\">$WM</span>|g" "$f"
    # "About the product" link points at the stripped /affilirank page — remove it.
    sed -i "s|<a href=\"https://affilirank\.com/affilirank\"[^>]*>About the product</a>||g" "$f"
    sed -i "s/AffiliRank/$BRAND_REP/g" "$f"
    if [ -n "$HOST" ]; then
      sed -i "s/affilirank\.com/$HOST/g" "$f"
    fi
    # Tagline: the footer uses "Affiliate deal engine. All rights reserved."
    # — handle that exact phrase first, then any remaining bare occurrences.
    if [ -n "$TAGLINE" ]; then
      sed -i "s|Affiliate deal engine\. All rights reserved\.|$TAGLINE_REP All rights reserved.|g" "$f"
      sed -i "s|Affiliate deal engine|$TAGLINE_REP|g" "$f"
    fi
  done

  # Inject the runtime brand override into every funnel page.
  for f in "$FUNNEL_DIR"/*.html; do
    if ! grep -q 'src="brand.js"' "$f"; then
      sed -i "s|</body>|<script src=\"brand.js\"></script></body>|" "$f"
    fi
  done

  # Generate the white-label funnel brand (logo, links, wordmark, year).
  cat > "$FUNNEL_DIR/brand.js" <<EOF
/* Generated by scripts/white-label-build.sh — white-label funnel brand. */
window.WHITE_LABEL_BRAND = {
  name: $(js_str "$BRAND_NAME"),
  tagline: $(js_str "$TAGLINE"),
  logo: $(js_str "$LOGO"),
  url: $(js_str "$SITE_URL_VAL"),
  blogUrl: $(js_str "${SITE_URL_VAL%/}/blog"),
  adminUrl: $(js_str "${SITE_URL_VAL%/}/admin"),
};
(function () {
  var B = window.WHITE_LABEL_BRAND || {};
  function ready(fn) {
    if (document.readyState === "loading") {
      document.addEventListener("DOMContentLoaded", fn);
    } else {
      fn();
    }
  }
  function esc(s) {
    return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
  }
  function wordmarkHtml(name) {
    var words = String(name).trim().split(/\\s+/);
    var last = words.pop() || "";
    return words.map(esc).join(" ") + (words.length ? " " : "") + "<span>" + esc(last) + "</span>";
  }
  ready(function () {
    if (!B.name) return;
    var wm = document.querySelector(".brand .wordmark");
    if (wm) wm.innerHTML = wordmarkHtml(B.name);
    var tag = document.querySelector(".brand .tag");
    if (tag && B.tagline && tag.textContent.trim() === "Affiliate deal engine") {
      tag.textContent = B.tagline;
    }
    if (B.logo) {
      var svg = document.querySelector(".brand svg");
      if (svg) {
        var img = document.createElement("img");
        img.src = B.logo;
        img.alt = B.name || "";
        img.className = "brand-logo";
        img.style.height = "26px";
        img.style.width = "auto";
        svg.replaceWith(img);
      }
    }
    document.querySelectorAll("a[href]").forEach(function (a) {
      var h = a.getAttribute("href") || "";
      if (!/^https?:/.test(h)) return;
      var path = h.replace(/^https?:\\/\\/[^/]+/, "");
      var target = null;
      if (path === "") target = B.url;
      else if (path.indexOf("/blog") === 0) target = B.blogUrl;
      else if (path.indexOf("/admin") === 0) target = B.adminUrl;
      if (target !== null) {
        if (target) a.setAttribute("href", target);
        else a.style.display = "none";
      }
    });
    var y = document.getElementById("year");
    if (y) y.textContent = new Date().getFullYear();
  });
})();
EOF
  echo "  wrote $FUNNEL_DIR/brand.js"
fi

echo "> Building (NEXT_PUBLIC_SHOW_PRODUCT_PAGE=${NEXT_PUBLIC_SHOW_PRODUCT_PAGE:-unset})"
npx next build
